markdown: rdiscount
pygments: true
permalink: /:title
rdiscount:
  extensions: [smart]
title : VICTOR
tagline: "Awkward Vampire of Awkward"
production_url : http://awkwardvampire.github.com
description: "Victor wants all the awkward... every last drop of it."
disqus_shortname: 
analytics: 
gauges: 
author :
  name : Victor Vampire Awkward
  github : awkwardvampire
  twitter : awkward_vampire
  email: awkwardvampire@gmail.com
paginate: 1
paginate_path: page:num